// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_clear_10_level = "CgkIjav3uvwdEAIQAQ"; // <GPGSID>
        public const string achievement_clear_50_level = "CgkIjav3uvwdEAIQAg"; // <GPGSID>
        public const string achievement_clear_100_level = "CgkIjav3uvwdEAIQAw"; // <GPGSID>
        public const string achievement_clear_300_level = "CgkIjav3uvwdEAIQBA"; // <GPGSID>
        public const string achievement_clear_500_level = "CgkIjav3uvwdEAIQBQ"; // <GPGSID>
        public const string achievement_clear_700_level = "CgkIjav3uvwdEAIQBg"; // <GPGSID>
        public const string achievement_clear_1000_level = "CgkIjav3uvwdEAIQBw"; // <GPGSID>
        public const string achievement_clear_1500_level = "CgkIjav3uvwdEAIQCA"; // <GPGSID>
        public const string achievement_clear_2000_level = "CgkIjav3uvwdEAIQCQ"; // <GPGSID>
        public const string achievement_clear_2500_level = "CgkIjav3uvwdEAIQCg"; // <GPGSID>
        public const string achievement_clear_3000_level = "CgkIjav3uvwdEAIQCw"; // <GPGSID>
        
        public const string achievement_collect_100_stars = "CgkIjav3uvwdEAIQDA"; // <GPGSID>
        public const string achievement_collect_200_stars = "CgkIjav3uvwdEAIQDQ"; // <GPGSID>
        public const string achievement_collect_300_stars = "CgkIjav3uvwdEAIQDg"; // <GPGSID>
        public const string achievement_collect_500_stars = "CgkIjav3uvwdEAIQDw"; // <GPGSID>
        public const string achievement_collect_700_stars = "CgkIjav3uvwdEAIQEA"; // <GPGSID>
        public const string achievement_collect_900_stars = "CgkIjav3uvwdEAIQEQ"; // <GPGSID>
        public const string achievement_collect_1000_stars = "CgkIjav3uvwdEAIQEg"; // <GPGSID>
        public const string achievement_collect_1500_stars = "CgkIjav3uvwdEAIQEw"; // <GPGSID>
        public const string achievement_collect_2000_stars = "CgkIjav3uvwdEAIQFA"; // <GPGSID>
        public const string achievement_collect_3000_stars = "CgkIjav3uvwdEAIQFQ"; // <GPGSID>
}

